ui: creating register ui
TommyPurba/Infinitum pull request #12
Opened 2023-09-20 04:05 UTC by dysandi

Component Register UI sudah dibuat

2023-09-20 04:50 UTC, indrazm commented on src/app/page.js
Remove the <div> it's redundant.

2023-09-20 04:51 UTC, indrazm commented on src/styles/globals.css
Your class name is not good. if it's input try to use ".input" instead of ".inp"
For ".inp" it should not inside @layer base.
It should inside @layer components.

2023-09-20 04:51 UTC, indrazm requested changes
I have made a comments.
Keep it up!

2023-09-20 08:23 UTC, dysandi commented on src/app/page.js
mas ini redundant di line brpa ya?

2023-09-20 13:09 UTC, indrazm commented on src/app/page.js
Sorry, remove the DIV. 5 and 7

2023-09-20 13:28 UTC, dysandi commented
mr @indrazm all changes have done

2023-09-21 03:03 UTC, indrazm approved these changes
LGTM

2023-09-21 03:06 UTC, indrazm commented
@dysandi @TommyPurba 
Please check with `npm run build` in local.
The deployment is failed in server.

2023-09-21 05:04 UTC, dysandi commented
<img width="1440" alt="Screenshot 2023-09-21 at 11 19 37" src="https://github.com/TommyPurba/Infinitum/assets/98368726/a53071c9-60cb-42cb-a970-dd243e40105b">

this is the result after npm run build mr @indrazm

2023-09-22 07:25 UTC, merged